version: '3'
services:
  node1:
    command: --datadir  /root/data --nodiscover --syncmode full --nodekey /root/files/priv.key
      --port 30313 --http --http.addr "0.0.0.0" --http.corsdomain="*" --http.port
      8503 --http.vhosts="*" --http.api db,eth,net,web3,admin,personal,miner,signer:insecure_unlock_protect  --networkid
      1234 --unlock 0 --password /root/files/password --mine --allow-insecure-unlock
    hostname: node_1
    image: ethereum/client-go
    ports:
    - 30313:30313
    - 8503:8503
    volumes:
    - ./nodes/node_1/keys/password:/root/files/password:ro
    - ./nodes/node_1/keys/priv.key:/root/files/priv.key:ro
    - ./nodes/node_1/data:/root/data:rw
  node2:
    command: --datadir  /root/data --nodiscover --syncmode full --nodekey /root/files/priv.key
      --port 30314 --http --http.addr "0.0.0.0" --http.corsdomain="*" --http.port
      8504 --http.vhosts="*" --http.api db,eth,net,web3,admin,personal,miner,signer:insecure_unlock_protect  --networkid
      1234 --unlock 0 --password /root/files/password --mine --allow-insecure-unlock
    hostname: node_2
    image: ethereum/client-go
    ports:
    - 30314:30314
    - 8504:8504
    volumes:
    - ./nodes/node_2/keys/password:/root/files/password:ro
    - ./nodes/node_2/keys/priv.key:/root/files/priv.key:ro
    - ./nodes/node_2/data:/root/data:rw
  node3:
    command: --datadir  /root/data --nodiscover --syncmode full --nodekey /root/files/priv.key
      --port 30315 --http --http.addr "0.0.0.0" --http.corsdomain="*" --http.port
      8505 --http.vhosts="*" --http.api db,eth,net,web3,admin,personal,miner,signer:insecure_unlock_protect  --networkid
      1234 --unlock 0 --password /root/files/password --mine --allow-insecure-unlock
    hostname: node_3
    image: ethereum/client-go
    ports:
    - 30315:30315
    - 8505:8505
    volumes:
    - ./nodes/node_3/keys/password:/root/files/password:ro
    - ./nodes/node_3/keys/priv.key:/root/files/priv.key:ro
    - ./nodes/node_3/data:/root/data:rw
  node4:
    command: --datadir  /root/data --nodiscover --syncmode full --nodekey /root/files/priv.key
      --port 30316 --http --http.addr "0.0.0.0" --http.corsdomain="*" --http.port
      8506 --http.vhosts="*" --http.api db,eth,net,web3,admin,personal,miner,signer:insecure_unlock_protect  --networkid
      1234 --unlock 0 --password /root/files/password --mine --allow-insecure-unlock
    hostname: node_4
    image: ethereum/client-go
    ports:
    - 30316:30316
    - 8506:8506
    volumes:
    - ./nodes/node_4/keys/password:/root/files/password:ro
    - ./nodes/node_4/keys/priv.key:/root/files/priv.key:ro
    - ./nodes/node_4/data:/root/data:rw
  litemonitor:
    image: alethio/ethereum-lite-explorer
    depends_on:
      - node1
    environment:
      - APP_NODE_URL=http://node1:8503
    ports:
    - 8001:80
  
